// create 6 digit code number
const randomCode = Math.floor(Math.random() * 6);
export const products = [
  {
    code: randomCode,
    title: "Collete Stretch Linen Stretch Linen Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 0,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 0,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
  {
    code: randomCode,
    title: "Collete Stretch Linen ",
    category: "Minidress",
    price: 69,
    quantity: 10,
    img: "https://tse4.mm.bing.net/th?id=OIP.51RNGQ5rSUtPzF0EQdOkDwHaJ4&pid=Api&P=0&w=300&h=300",
  },
];
